### ISSUE TITLE
SpongePls not loading

### ISSUE THREAD

**Issue by JackCosens** [SilverCory/SpongePls#18]
[10:31:10 ERROR]: java.lang.reflect.InvocationTargetException
[10:31:10 ERROR]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:31:10 ERROR]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:31:10 ERROR]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:31:10 ERROR]: at java.lang.reflect.Method.invoke(Method.java:498)
[10:31:10 ERROR]: at co.ryred.spongepls.CustomClassLoader.loadClass(CustomClassLoader.java:88)
[10:31:10 ERROR]: at co.ryred.spongepls.SpongePlsPlugin.changeChild(SpongePlsPlugin.java:147)
[10:31:10 ERROR]: at co.ryred.spongepls.SpongePlsPlugin.onEnable(SpongePlsPlugin.java:109)
[10:31:10 ERROR]: at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261)
[10:31:10 ERROR]: at net.md_5.bungee.BungeeCord.start(BungeeCord.java:292)
[10:31:10 ERROR]: at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
[10:31:10 ERROR]: at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[10:31:10 ERROR]: Caused by: java.lang.LinkageError: loader (instance of sun/misc/Launcher$AppClassLoader): attempted duplicate class definition for name: "net/md_5/bungee/netty/HandlerBoss"
[10:31:10 ERROR]: at java.lang.ClassLoader.defineClass1(Native Method)
[10:31:10 ERROR]: at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[10:31:10 ERROR]: at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
[10:31:10 ERROR]: ... 11 more
[10:31:10 ERROR]: java.lang.NoSuchFieldException: invokableObj
[10:31:10 ERROR]: at java.lang.Class.getDeclaredField(Class.java:2070)
[10:31:10 ERROR]: at co.ryred.spongepls.SpongePlsPlugin.changeChild(SpongePlsPlugin.java:149)
[10:31:10 ERROR]: at co.ryred.spongepls.SpongePlsPlugin.onEnable(SpongePlsPlugin.java:109)
[10:31:10 ERROR]: at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261)
[10:31:10 ERROR]: at net.md_5.bungee.BungeeCord.start(BungeeCord.java:292)
[10:31:10 ERROR]: at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
[10:31:10 ERROR]: at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

Using a variety of different bungeecord versions to test with - All of them spit out this error on startup.

**Comment by JackCosens** [comment]
https://hastebin.com/ilijikoteb.md

For people who may complain about how it looks.
